'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminSettings

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''TxtAmountRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAmountRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonCostUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCostUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TxtClientRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtClientRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtClient As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonClientNameUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonClientNameUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TxtorderstartRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtorderstartRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Txtorderstart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtorderstart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonOrderStartUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonOrderStartUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TxtorderendRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtorderendRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Txtorderend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtorderend As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonOrderEndUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonOrderEndUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TxtMsgRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMsgRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMsg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonMsgUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonMsgUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonMsgClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonMsgClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TxtDisableRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDisableRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtDisable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDisable As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonDisableUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDisableUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonDisableClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDisableClear As Global.System.Web.UI.WebControls.Button
End Class
